global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-enterprise-accelerator-uk-official
  regions:
    - us-west-2
  reporting: true
tests:
  defaults:
    parameter_input: defaults.json
    template_file: main.template
